### ISSUE TITLE
redefining named object

### ISSUE THREAD

**Issue by mpcabd** [marinho/geraldo#14]
When I try to generate two reports in one file I get this error:

> File "C:\Python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 516, in Reference
> raise ValueError, "redefining named object: "+repr(name)
> ValueError: redefining named object: 'toUnicodeCMap:AAAAAA+ArialMT'

``` python
my_report = MyFamilyReport(queryset=family)
c = my_report.generate_by(PDFGenerator, return_canvas=True, filename = 'family.pdf')
my_report = MyFamilyReport(queryset=family1)
my_report.generate_by(PDFGenerator, canvas = c)
```

**Comment by techscientist** [comment]
I have the same problem. Any updates?

**Comment by igor-olikh** [comment]
Hi @mpcabd 
Have you found what was the problem and how you fixed it?

**Comment by igor-olikh** [comment]
@techscientist ?

**Comment by mpcabd** [comment]
I don't really remember if I have solved this or not, it's been too long.
