### ISSUE TITLE
Poorly documented get_value and get_text

### ISSUE THREAD

**Issue by pkaczynski** [marinho/geraldo#20]
I was trying to make summary value printed in words. For example I want to print an invoice with summary value verbally like this:

Product | Value
X | 100
Y | 200

Sum: 300 (verbally: three hundred)

I did not find a way to do this. Display format does not allow to perform any functions on the value beeing displayed. On the other hand I cannot perform verbalizing function in get_value since it is summing those values. I was hoping on get_text, but this is poorly documented, no example given. Please either improve the documentation or at least give some examples on using get_text.

**Comment by samkuehn** [comment]
I am having the same issue.  Did you ever figure this out?

**Comment by samkuehn** [comment]
I figured this out there was a bug in the code see #22

**Comment by pkaczynski** [comment]
Thanks for the info. Will update soon.
